
name: gfwPAC_update

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
  generate_pac:
    name: Generate PAC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 替换成您希望使用的 Python 版本

      - name: Execute Python Script
        run: |
            python ./gfw-pac.py 
            
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your_email@example.com"
          git add gfw.pac
          git commit -m "update pac"
          git remote set-url origin https://github.com/lixiansheng828/gfwPAC.git  # 替换为您的仓库 URL
          git push

