
name: gfwPAC_update

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
  run_python_script:
    name: Run Python Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Execute Python Script
        run: |
            chmod +x run_pac
            ./run_pac

