
name: gfwPAC_update

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
  generate_pac:
    name: Generate PAC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 替换成您希望使用的 Python 版本

      - name: Execute Python Script
        run: |
            python ./gfw-pac.py 
      - name: Commit changes
        run: |
            git config --local user.email "676252316@qq.com"
            git config --local user.name "lixiansheng828"
            git add gfw.pac
            git commit -m "Update afw.pac"  # 可以根据需要修改提交信息

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ ${{ secrets.GITHUB_TOKEN }}
