
name: gfwPAC_update

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
  generate_pac:
    name: Generate PAC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 替换成您希望使用的 Python 版本

      - name: Execute Python Script
        run: |
            python ./gfw-pac.py 
            rm gfw.pac
            cp gfw.pac $GITHUB_WORKSPACE/gfw.pac  

